"""AI assistant schemas."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.core.enums import AssistantRole


class AssistantMessageOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    role: AssistantRole
    content: str
    filters: dict | None = None
    citations: list[int] = Field(default_factory=list)
    created_at: datetime


class AssistantConversationOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    message_count: int
    last_message_at: datetime | None = None
    created_at: datetime
    messages: list[AssistantMessageOut] = Field(default_factory=list)


class AssistantConversationCreate(BaseModel):
    title: str = Field(default="New conversation", max_length=255)


class AssistantQuery(BaseModel):
    query: str = Field(min_length=1, max_length=2000)


class AssistantResult(BaseModel):
    """A retrieved email reference returned alongside an answer."""

    id: int
    subject: str
    sender: str
    received_at: datetime | None = None
    category: str | None = None
    priority: str | None = None
    sentiment: str | None = None
    reply_required: bool | None = None
    summary: str = ""
    is_read: bool = False


class AssistantAnswer(BaseModel):
    conversation_id: int | None = None
    message: AssistantMessageOut
    # Validated structured filters that were actually applied by the backend.
    applied_filters: dict = Field(default_factory=dict)
    total_matches: int = 0
    results: list[AssistantResult] = Field(default_factory=list)
    answer: str
    # True when the answer was assembled deterministically from retrieved
    # records instead of being generated by a language model.
    deterministic: bool = False
