"""initial schema

Revision ID: 33760a0273dc
Revises: 
Create Date: 2026-10-01 01:06:03.956043
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33760a0273dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_config'))
    )
    op.create_index(op.f('ix_category_config_created_at'), 'category_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_category_config_key'), 'category_config', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('assistant_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assistant_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_conversations'))
    )
    op.create_index(op.f('ix_assistant_conversations_created_at'), 'assistant_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_assistant_conversations_user_id'), 'assistant_conversations', ['user_id'], unique=False)
    op.create_index('ix_assistant_conversations_user_id_updated_at', 'assistant_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens'))
    )
    op.create_index(op.f('ix_auth_tokens_created_at'), 'auth_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index('ix_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_key', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_unread', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_threads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_threads')),
    sa.UniqueConstraint('user_id', 'thread_key', name='uq_email_threads_user_id_thread_key')
    )
    op.create_index(op.f('ix_email_threads_created_at'), 'email_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_email_threads_user_id'), 'email_threads', ['user_id'], unique=False)
    op.create_index('ix_email_threads_user_id_last_message_at', 'email_threads', ['user_id', 'last_message_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled_types', sa.JSON(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('daily_digest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences'))
    )
    op.create_index(op.f('ix_notification_preferences_created_at'), 'notification_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_tokens'))
    )
    op.create_index(op.f('ix_session_tokens_token_hash'), 'session_tokens', ['token_hash'], unique=True)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_config_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_index(op.f('ix_system_config_created_at'), 'system_config', ['created_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_reply_tone', sa.String(length=32), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('notification_channels', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.create_index(op.f('ix_user_preferences_created_at'), 'user_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], name=op.f('fk_assistant_messages_conversation_id_assistant_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assistant_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_messages'))
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assistant_messages_created_at'), 'assistant_messages', ['created_at'], unique=False)
    op.create_index('ix_assistant_messages_user_id', 'assistant_messages', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('to', sa.JSON(), nullable=False),
    sa.Column('cc', sa.JSON(), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('preview', sa.String(length=300), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('direction', sa.String(length=16), server_default='inbound', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attachment_names', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('processing_error', sa.String(length=512), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], name=op.f('fk_emails_thread_id_email_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emails_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails')),
    sa.UniqueConstraint('user_id', 'dedupe_hash', name='uq_emails_user_id_dedupe_hash')
    )
    op.create_index(op.f('ix_emails_created_at'), 'emails', ['created_at'], unique=False)
    op.create_index(op.f('ix_emails_from_address'), 'emails', ['from_address'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=False)
    op.create_index(op.f('ix_emails_processing_status'), 'emails', ['processing_status'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_subject'), 'emails', ['subject'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_index('ix_emails_user_id_direction', 'emails', ['user_id', 'direction'], unique=False)
    op.create_index('ix_emails_user_id_is_archived', 'emails', ['user_id', 'is_archived'], unique=False)
    op.create_index('ix_emails_user_id_is_deleted_received_at', 'emails', ['user_id', 'is_deleted', 'received_at'], unique=False)
    op.create_index('ix_emails_user_id_received_at', 'emails', ['user_id', 'received_at'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_text', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date_estimated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_action_items_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    op.create_index(op.f('ix_action_items_created_at'), 'action_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_items_due_date'), 'action_items', ['due_date'], unique=False)
    op.create_index('ix_action_items_email_id', 'action_items', ['email_id'], unique=False)
    op.create_index(op.f('ix_action_items_user_id'), 'action_items', ['user_id'], unique=False)
    op.create_index('ix_action_items_user_id_status_due_date', 'action_items', ['user_id', 'status', 'due_date'], unique=False)
    op.create_table('ai_error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retryable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_ai_error_logs_email_id_emails'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_error_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_error_logs'))
    )
    op.create_index('ix_ai_error_logs_created_at', 'ai_error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_error_logs_email_id'), 'ai_error_logs', ['email_id'], unique=False)
    op.create_index('ix_ai_error_logs_error_code', 'ai_error_logs', ['error_code'], unique=False)
    op.create_index(op.f('ix_ai_error_logs_user_id'), 'ai_error_logs', ['user_id'], unique=False)
    op.create_table('ai_usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_ai_usage_records_email_id_emails'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_records_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_records'))
    )
    op.create_index(op.f('ix_ai_usage_records_created_at'), 'ai_usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_records_email_id'), 'ai_usage_records', ['email_id'], unique=False)
    op.create_index('ix_ai_usage_records_purpose_created_at', 'ai_usage_records', ['purpose', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_records_user_id'), 'ai_usage_records', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_records_user_id_created_at', 'ai_usage_records', ['user_id', 'created_at'], unique=False)
    op.create_table('email_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), server_default='other', nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('priority_reason', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('reply_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('action_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('summary_short', sa.Text(), nullable=False),
    sa.Column('summary_detailed', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('unresolved_issues', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_email_analysis_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_analysis_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_analysis')),
    sa.UniqueConstraint('email_id', name='uq_email_analysis_email_id')
    )
    op.create_index(op.f('ix_email_analysis_created_at'), 'email_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_analysis_email_id'), 'email_analysis', ['email_id'], unique=True)
    op.create_index(op.f('ix_email_analysis_user_id'), 'email_analysis', ['user_id'], unique=False)
    op.create_index('ix_email_analysis_user_id_action_required', 'email_analysis', ['user_id', 'action_required'], unique=False)
    op.create_index('ix_email_analysis_user_id_category', 'email_analysis', ['user_id', 'category'], unique=False)
    op.create_index('ix_email_analysis_user_id_priority', 'email_analysis', ['user_id', 'priority'], unique=False)
    op.create_index('ix_email_analysis_user_id_reply_required', 'email_analysis', ['user_id', 'reply_required'], unique=False)
    op.create_index('ix_email_analysis_user_id_sentiment', 'email_analysis', ['user_id', 'sentiment'], unique=False)
    op.create_table('suggested_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('original_body', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_suggested_replies_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], name=op.f('fk_suggested_replies_thread_id_email_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_suggested_replies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggested_replies'))
    )
    op.create_index(op.f('ix_suggested_replies_created_at'), 'suggested_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_suggested_replies_email_id'), 'suggested_replies', ['email_id'], unique=False)
    op.create_index(op.f('ix_suggested_replies_user_id'), 'suggested_replies', ['user_id'], unique=False)
    op.create_index('ix_suggested_replies_user_id_email_id', 'suggested_replies', ['user_id', 'email_id'], unique=False)
    op.create_index('ix_suggested_replies_user_id_status', 'suggested_replies', ['user_id', 'status'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('value_normalized', sa.String(length=64), nullable=True),
    sa.Column('raw_phrase', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analysis.id'], name=op.f('fk_extracted_entities_analysis_id_email_analysis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_extracted_entities_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_extracted_entities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_entities'))
    )
    op.create_index(op.f('ix_extracted_entities_analysis_id'), 'extracted_entities', ['analysis_id'], unique=False)
    op.create_index('ix_extracted_entities_email_id', 'extracted_entities', ['email_id'], unique=False)
    op.create_index('ix_extracted_entities_user_id_field', 'extracted_entities', ['user_id', 'field'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action_items.id'], name=op.f('fk_notifications_action_id_action_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_notifications_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notifications_user_id_dedupe_key')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_email_id'), 'notifications', ['email_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read_created_at', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id_is_read_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_email_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_extracted_entities_user_id_field', table_name='extracted_entities')
    op.drop_index('ix_extracted_entities_email_id', table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_analysis_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index('ix_suggested_replies_user_id_status', table_name='suggested_replies')
    op.drop_index('ix_suggested_replies_user_id_email_id', table_name='suggested_replies')
    op.drop_index(op.f('ix_suggested_replies_user_id'), table_name='suggested_replies')
    op.drop_index(op.f('ix_suggested_replies_email_id'), table_name='suggested_replies')
    op.drop_index(op.f('ix_suggested_replies_created_at'), table_name='suggested_replies')
    op.drop_table('suggested_replies')
    op.drop_index('ix_email_analysis_user_id_sentiment', table_name='email_analysis')
    op.drop_index('ix_email_analysis_user_id_reply_required', table_name='email_analysis')
    op.drop_index('ix_email_analysis_user_id_priority', table_name='email_analysis')
    op.drop_index('ix_email_analysis_user_id_category', table_name='email_analysis')
    op.drop_index('ix_email_analysis_user_id_action_required', table_name='email_analysis')
    op.drop_index(op.f('ix_email_analysis_user_id'), table_name='email_analysis')
    op.drop_index(op.f('ix_email_analysis_email_id'), table_name='email_analysis')
    op.drop_index(op.f('ix_email_analysis_created_at'), table_name='email_analysis')
    op.drop_table('email_analysis')
    op.drop_index('ix_ai_usage_records_user_id_created_at', table_name='ai_usage_records')
    op.drop_index(op.f('ix_ai_usage_records_user_id'), table_name='ai_usage_records')
    op.drop_index('ix_ai_usage_records_purpose_created_at', table_name='ai_usage_records')
    op.drop_index(op.f('ix_ai_usage_records_email_id'), table_name='ai_usage_records')
    op.drop_index(op.f('ix_ai_usage_records_created_at'), table_name='ai_usage_records')
    op.drop_table('ai_usage_records')
    op.drop_index(op.f('ix_ai_error_logs_user_id'), table_name='ai_error_logs')
    op.drop_index('ix_ai_error_logs_error_code', table_name='ai_error_logs')
    op.drop_index(op.f('ix_ai_error_logs_email_id'), table_name='ai_error_logs')
    op.drop_index('ix_ai_error_logs_created_at', table_name='ai_error_logs')
    op.drop_table('ai_error_logs')
    op.drop_index('ix_action_items_user_id_status_due_date', table_name='action_items')
    op.drop_index(op.f('ix_action_items_user_id'), table_name='action_items')
    op.drop_index('ix_action_items_email_id', table_name='action_items')
    op.drop_index(op.f('ix_action_items_due_date'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_created_at'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_emails_user_id_received_at', table_name='emails')
    op.drop_index('ix_emails_user_id_is_deleted_received_at', table_name='emails')
    op.drop_index('ix_emails_user_id_is_archived', table_name='emails')
    op.drop_index('ix_emails_user_id_direction', table_name='emails')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_subject'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_processing_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_from_address'), table_name='emails')
    op.drop_index(op.f('ix_emails_created_at'), table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_assistant_messages_user_id', table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_created_at'), table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_created_at'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_system_config_created_at'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_session_tokens_token_hash'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_created_at'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_email_threads_user_id_last_message_at', table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_user_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_created_at'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index('ix_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_created_at'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_assistant_conversations_user_id_updated_at', table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_user_id'), table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_created_at'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_category_config_key'), table_name='category_config')
    op.drop_index(op.f('ix_category_config_created_at'), table_name='category_config')
    op.drop_table('category_config')
    # ### end Alembic commands ###
